### ISSUE TITLE
Space between multiplication and division operators is clamped with custom properties

### ISSUE THREAD

**Issue by joneff** [postcss/postcss-calc#127]
Using postcss-calc v7.0.5

```css
/* Input */
.selector {
    bottom: calc( var(--a, 0) * 1% );
    height: calc( (var(--b, 0) - var(--a, 0)) * 1% );
}

/* output */
.selector {
    bottom: calc(var(--a, 0)*1%);
    height: calc((var(--b, 0) - var(--a, 0))*1%);
}
```

While multiplication and division still work, various tools are reporting it is invalid.
