### ISSUE TITLE
Fails with SCSS variables

### ISSUE THREAD

**Issue by manokara** [postcss/postcss-calc#141]
The following snippet fails:

```css
#main {
    /* ... */
    height: calc((var(--vh, 1vh) * 100) - ($navbar-height + $statusbar-height));
}
```

The error points exactly to the dollar sign. I can work around it with normal CSS variables:

```css
#main {
    /* ... */
    --navbar-height: $navbar-height;
    --statusbar-height: $statusbar-height;
    height: calc((var(--vh, 1vh) * 100) - (var(--navbar-height) + var(--statusbar-height)));
}
```

For context, `postcss` is being used by  `cssnano` which is being used by `vue-cli`. It seems to me that `postcss-calc` is being run before SCSS variables are evaluated. I'm not sure if this is intended or is something this package has to explicity account for.
