### ISSUE TITLE
"ParserError: Syntax Error" with negative multiplication and vars

### ISSUE THREAD

**Issue by frans-vectra** [postcss/postcss-calc#142]
Hi, I've been getting a parse syntax error while trying to make a production build of [Vue Storefront 2 Magento theme](https://github.com/vuestorefront/template-magento) project.

The error specifically occurs when trying to parse something like `calc(var(--my-var) * -1)`;

e.g.

```CSS
:root {
  --my-var: 12px;
}

.my-class {
  margin: 0 calc(var(--my-var) * -1) 0 0;
}
```

By just changing the order of the terms in the calc statement it works correctly;

e.g.

```CSS
:root {
  --my-var: 12px;
}

.my-class {
  margin: 0 calc(-1 * var(--my-var)) 0 0;
}
```

### Environment

- macos `v11.6`
- node `v14.16.1`
- npm `v6.14.12`
- yarn `v1.22.10`
- vuestorefront/template-magento `v1.0.0-rc.3`
- postcss `v7.0.32`

### Reproduction steps

1. `$ npx @vue-storefront/cli init`
2. Select the `Magento 2 (beta)` integration option
3. Copy the `.env.example` as `.env` and update the Magento integration URLs (`MAGENTO_GRAPHQL`, `MAGENTO_EXTERNAL_CHECKOUT_URL`)
3. `$ yarn install`
4. `$ yarn dev` (everything works in dev mode)
4. `$ yarn build` (build fails with the postcss errors)
