### ISSUE TITLE
[Question] Floor and Ceil?

### ISSUE THREAD

**Issue by oleersoy** [postcss/postcss-calc#18]
Hi,

I'm wondering if there's a way to round pixel calculations up or down.  For example the following:

```css
:root {
  --fontSizeUnit: 1px;
  --fontSizeRatio: 0.75;
}

h1 {
  font-size: var(--fontSize);
}

Will come out as:

```css
h1 {
font-size: 0.75px;
}
```
I would like it to be:
``` css
h1 {
font-size: 1px;
}

```

TIA,
Ole
