### ISSUE TITLE
Support for multiline calc()

### ISSUE THREAD

**Issue by alienlebarge** [postcss/postcss-calc#26]
Currently, postcss-calc only do the job when `calc()` value is on one line. But if it's on more that one line, it doesn't work.

#### One line
*input.css*
```css
h1 {
    font-size: calc( 1rem * 1.26 * 1.26 * 1.26 );
}
```

*output.css*
```css
h1 {
    font-size: font-size: 2.00038rem;
}
```
#### Multi line
*input.css*
```css
h1 {
    font-size: calc( 
                       1rem 
                       * 1.26 
                       * 1.26
                       * 1.26
                   );
}
```

*output.css*
```css
h1 {
    font-size: calc( 
                       1rem 
                       * 1.26 
                       * 1.26 
                       * 1.26 
                   );
}
```

Is it possible to support 

---

There's a workaround in the meantime.
I use *[perfectionist](https://github.com/ben-eb/perfectionist)* before *postcss-calc*
