### ISSUE TITLE
Add gnuMessage style with source of the error

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-calc#3]
``` css
body { font-size: calc(var(--fontSize) * 1.2; }
```

returns `SyntaxError: calc(): missing closing ')' in the value 'calc(1rem * 1.2'`

We need to add file:line:column
