### ISSUE TITLE
`NaN` value when reducing division with custom property

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-calc#44]
https://github.com/MoOx/postcss-cssnext/issues/427

Input:
```css
:root {
    --foo: calc(var(--bar) / 8);
}
```
Output:
```css
:root {
    --foo: NaN;
}
```
