### ISSUE TITLE
support constant() and env()

### ISSUE THREAD

**Issue by rodneyrehm** [postcss/postcss-calc#48]
Hey there,

in my build setup ([optimize-css-assets-webpack-plugin](https://www.npmjs.com/package/optimize-css-assets-webpack-plugin) using [cssnano](http://cssnano.co/)) I had to disable postcss-calc because it was killing any `calc()` that use `constant()` and `env()` (see [Designing Websites for iPhone X](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)). Note how the `100%` turned into `1`:

### Input

```css
body {
  height: 100%;
  /* iPhone X on iOS 11.0 */
  height: calc(100% + constant(safe-area-inset-top) + constant(safe-area-inset-bottom));
  /* iPhone X on iOS 11+ */
  height: calc(100% + env(safe-area-inset-top) + env(safe-area-inset-bottom));
}
```

### Output

```css
body {
  height: 100%;
  height: calc(1 + constant(safe-area-inset-top) + constant(safe-area-inset-bottom));
  height: calc(1 + env(safe-area-inset-top) + env(safe-area-inset-bottom))
}
```

I tried producing a minimal test case with only postcss-calc, but all I got was:

```
➜  node index.js
/…/post-css-calc/node_modules/postcss/lib/lazy-result.js:280
            throw error;
            ^

Error: Parse error on line 1:
100% + constant(safe-area-i
-------^
Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX'
    at Parser.parseError (/…/post-css-calc/node_modules/reduce-css-calc/dist/parser.js:160:21)
    at Parser.parse (/…/post-css-calc/node_modules/reduce-css-calc/dist/parser.js:226:22)
    at /…/post-css-calc/node_modules/reduce-css-calc/dist/index.js:35:30
    at walk (/…/post-css-calc/node_modules/postcss-value-parser/lib/walk.js:15:13)
    at ValueParser.walk (/…/post-css-calc/node_modules/postcss-value-parser/lib/index.js:18:5)
    at exports.default (/…/post-css-calc/node_modules/reduce-css-calc/dist/index.js:29:51)
    at transformValue (/…/post-css-calc/node_modules/postcss-calc/dist/lib/transform.js:24:45)
    at exports.default (/…/post-css-calc/node_modules/postcss-calc/dist/lib/transform.js:54:100)
    at /…/post-css-calc/node_modules/postcss-calc/dist/index.js:28:52
    at /…/post-css-calc/node_modules/postcss/lib/container.js:144:26
```
