### ISSUE TITLE
Precision for nested calc is not accurate

### ISSUE THREAD

**Issue by andreymal** [postcss/postcss-calc#66]
```css
.foo {
  width: calc(100% / 3 * 3);
  height: calc(calc(100% / 3) * 3);
}
```

Expected output:

```css
.foo {
  width: 100%;
  height: 100%;
}
```

Actual output:

```css
.foo {
  width: 100%;
  height: 99.99999%;
}
```

[reduce-css-calc is also affected](https://github.com/MoOx/reduce-css-calc/issues/51)

Note that [it works in Firefox and Chrome](https://jsfiddle.net/3qtd127o/):

![](https://i.imgur.com/J7qSiE1.png)
